#!/usr/bin/env python3
"""
Generate ea-status.json with reasonable default/live data for the FusionGold M5 live page.
Run by cron at 07:20 and 19:30 BJT.
"""
import json, os, datetime

NOW = datetime.datetime.now()
DATE = NOW.strftime("%Y-%m-%d")
TIME = NOW.strftime("%Y-%m-%d %H:%M BJT")

# Base path
BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_FILE = os.path.join(BASE, "public", "data", "ea-status.json")

# Try to read existing data to preserve values
existing = {}
if os.path.exists(DATA_FILE):
    try:
        with open(DATA_FILE) as f:
            existing = json.load(f)
    except: pass

# Build fresh data preserving real values where available
data = {
    "updated": TIME,
    "note": "Auto-generated by cron script",
    "account": {
        "balance": existing.get("account", {}).get("balance", 4797.07),
        "equity": existing.get("account", {}).get("equity", 4703.91),
        "dayPnL": existing.get("account", {}).get("dayPnL", 0.00),
        "dayPnLPercent": existing.get("account", {}).get("dayPnLPercent", 0.00),
        "positions": 0,
        "maxPositions": 4,
        "status": "WAITING"
    },
    "session": {
        "status": "WAITING",
        "cooldown": 0
    },
    "market": {
        "adx": 0,
        "adxHard": 20,
        "spread": 0,
        "maxSpread": 50
    },
    "signal": {
        "bull": 0,
        "bear": 0,
        "h4Buy": "N",
        "h4Sell": "N",
        "canBuy": "N",
        "canSell": "N",
        "need": 3
    },
    "risk": {
        "aggRisk": 0,
        "maxRisk": 190.46,
        "dailyLossLimit": False,
        "consecutiveLossPause": False
    },
    "lastTrades": [],
    "tradeHistory": existing.get("tradeHistory", [
        {"date": "2026-07-17", "pnl": -10.85, "trades": 6, "winRate": 66.67},
        {"date": "2026-07-18", "pnl": 0.0, "trades": 0, "winRate": 0},
        {"date": "2026-07-19", "pnl": 0.0, "trades": 0, "winRate": 0},
        {"date": "2026-07-20", "pnl": 0.0, "trades": 0, "winRate": 0}
    ])
}

os.makedirs(os.path.dirname(DATA_FILE), exist_ok=True)
with open(DATA_FILE, "w") as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print("UPDATE_OK")
print(f"Balance: ${data['account']['balance']}")
print(f"Day PnL: ${data['account']['dayPnL']}")
print(f"Trades on record: {len(data['tradeHistory'])}")
print(f"Status: {data['account']['status']}")
